spring:
  cloud:
    azure:
      eventhubs:
        connection-string: Endpoint=sb://eventhubsnamespace.servicebus.windows.net/;SharedAccessKeyName=eventhubssaspolicy;SharedAccessKey=OIXEkmbWRrRaywTcUIf9E9ecYB9ca1ygP+AEhI4SViY=;EntityPath=eventhubteste
        namespace: eventhubsnamespace
        processor:
          checkpoint-store:
            container-name: eventhubs-account-container
            account-name: storageaccounteventhubs
            account-key: B+AkM8RZOBpLf2ZS67MjbsXjsyJ6VQOsNCfaD9M0Q6okWwTB9FPMSX2ig+nG7SX1RgPe9UL5atHH+AStVwBJjQ==
    function:
      definition: consume
    stream:
      output-bindings: supply
      bindings:
        consume-in-0:
          destination: eventhubteste
          group: $Default
        supply-out-0:
          destination: eventhubteste
      eventhubs:
        bindings:
          consume-in-0:
            consumer:
              checkpoint:
                mode: RECORD
          supply-out-0:
            producer:
              sync: true
      default:
        producer:
          errorChannelEnabled: true