spring:
  cloud:
    azure:
      eventhubs:
        # Remover aspas extras na connection-string
        connection-string: ${AZURE_EVENTHUB_NAMESPACE_CONNECTION_STRING:Endpoint=sb://eventhubsnamespace.servicebus.windows.net/;SharedAccessKeyName=eventhubssaspolicy;SharedAccessKey=OIXEkmbWRrRaywTcUIf9E9ecYB9ca1ygP+AEhI4SViY=;EntityPath=eventhubteste}
        namespace: ${EVENT_HUBS_NAMESPACE:eventhubsnamespace}
        processor:
          checkpoint-store:
            container-name: storageaccounteventhubs
            account-name: eventhubsaccount
            account-key: ${AZURE_STORAGE_ACCOUNT_KEY:B+AkM8RZOBpLf2ZS67MjbsXjsyJ6VQOsNCfaD9M0Q6okWwTB9FPMSX2ig+nG7SX1RgPe9UL5atHH+AStVwBJjQ==}
    function:
      definition: consume
    stream:
      output-bindings: supply
      bindings:
        consume-in-0:
          destination: medium-eventhub
          group: $Default
        supply-out-0:
          destination: medium-eventhub
      eventhubs:
        bindings:
          consume-in-0:
            consumer:
              checkpoint:
                mode: RECORD
          supply-out-0:
            producer:
              sync: true
      default:
        producer:
          errorChannelEnabled: true
